### ISSUE TITLE
Potential Acquisitions Property Map (8/20-8/30)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/jldp_maprequests#4]
from MB:

aquisiiton targets around the Preserve… we got a few ..

- surfing cowboys
- point conception
- poets (san Julian?)
- sudden ranch
- all property off Jalama rd. leading up to Preserve

Do you think we can create an old school property target map – maybe with some simple information embedded for each property – value, size, coastline, strategy, next steps?  Something like this attached old school map but with some additional information.

![properties map](https://user-images.githubusercontent.com/9966696/43910854-c5d2ce92-9bb2-11e8-992b-8b8999947ef0.jpg)

see the Preserve Expnasion Plan section in https://docs.google.com/document/d/1mwiB8PQtFx8ID_YyxoLC5o7ceecIgIet9JmI3WHen34/edit?usp=sharing for details

**Comment by megrwebb** [comment]
@connorshank see the Preserve Expansion Plan section in https://docs.google.com/document/d/1mwiB8PQtFx8ID_YyxoLC5o7ceecIgIet9JmI3WHen34/edit?usp=sharing for details

Let's start by using current Santa Barbara parcel data to develop new ownership tracts in this area.  Once established, I can add these to our TRACTS layer and we can run the Conservation Accounting report to get a basic roll-up of ecological value for each property (8/17).

We'll need to work with @ka78 to have this up and running correctly on all data layers.

Map(s) to come later (8/20-8/30)

@bcohen27, can we start getting due dates like in gd_intern in the request titles?

Thanks!

**Comment by ka78** [comment]
Hey so, this map was made in 2004, before my time, but I did some sleuthing and can provide a little info:
- I found the plot here: N:\Central_Coast\Projects\Sba\Plots\sba_gav_west_site.jpg
- I don't see an mxd with a corresponding name here: N:\Central_Coast\Projects\Sba\Mxds\...?
- A common practice of ours is to have a mxd and a corresponding plot that use the exact same name so that we can find mxds that created specific maps, but that wasn't done for this map. It's possible there was a parent mxd that was used to create a set of maps (I see a bunch of maps that seem to be the same, just different extents).
- In 2017, we ran a script that created a txt for every mxd on carogis; the txt file lists all the data sources in the mxd (in case the mxd is corrupted because of our enterprise gdb upgrade in 2017)
- @connorshank if you're trying to find exact layers used in this map you could search the text files located in the Mxd folder referenced above using the DATE of the jpg as a clue, and find those with a similar data of the .jpg, and see if you can identify which layers were used... this is if you're wanting to recreate this map, or find specific old layers.

**Comment by bcohen27** [comment]
Information about two property owners:

"This is one of the landowners of a 1,000 acre ranch north of Jalama rd.

Mb


From: Sarah Tanguay <stanguay@TNC.ORG>
Date: Thursday, August 9, 2018 at 12:49 PM
To: Michael Bell <mbell@TNC.ORG>, JENNIFER Herrington <jherrington@TNC.ORG>, Moses Katkowski <mkatkowski@TNC.ORG>
Subject: Chris Kleveland & Pat Aoyama

Gang – 
Thanks for taking the time to meet with Chris & Pat yesterday.  
 
I got a nice note from Chris this morning, see below.  If you’d like to follow up with them now or in the future, here’s their contact info.  
•	Chris: chriskleveland@cox.net
•	Pat: paoyama@aol.com
 
Please note that they are in my portfolio as major gift prospects.  So, if you continue to have neighborly interactions with them, please keep me in the loop.
 
---
Sarah;
> 
> Thank you for your tour guide skills and hospitality yesterday—we had a thoroughly enjoyable day.  Meeting the new crew at Cojo was a very positive experience for me, as was learning more about the TNC mission there.  It can’t be understated, the situation is so much better now than under the past ‘regime’. I believe all your neighbors will be much relieved and welcoming.  
> 
> It’s obvious that Cojo has a huge opportunity to become an unparalleled resource for the positive.
> 
> Dig out that fancy birthday camera of yours and get some pics of the humpbacks and greys spyhopping off the lighthouse.  What a great thing you’re involved in.
> 
> Thanks again

**Comment by megrwebb** [comment]
Thanks @ka78. @connorshank let's meet next week to talk more about this request.  The first step will be getting the new ownership tracts for the map area above and comparing this with our old tract delineations.  I will update this where needed in our TRACTS dataset and probably include a few more.  When we get to the mapping part, I can help you locate data, etc.

**Comment by megrwebb** [comment]
@ka78 I'll need to work with you to make sure Conservation Accounting is healthy so we can run this report on these properties.

**Comment by megrwebb** [comment]
@connorshank here is a revised step-by-step outline of what I think is needed for this request.  @bcohen27 please update/revise based on what you know or think is needed. Going forward,  I think it probably makes the most sense for the both of you to coordinate on this request and I can chime in as needed.  I’m feeling like there are too many cooks in the kitchen!

1)	Develop new “Ownership Tracts” for this map area based on current SB county parcel data
a.	Use the “Coastal Santa Ynez Mountains” site boundary from CAP planning to select parcels that intersect this area
i.	Data located here: N:\Central_Coast\Projects\Sba\sba_CAP.mdb\CA
b.	Dissolve parcels by ownership (uncheck create multipart features). Note, don’t remove any parcels even if they are protected.
c.	Make copy of ownership tracts dataset with Dangermond Preserve parcels merged into one tract.  Do the same with Hollister Ranch (there might be others) and add Sudden Ranch parcels (see parcels
 below). Note, I think it is important to delineate this ranch by parcels in case we want to run the conservation accounting report and need to compare it with other ownership tracts.  For mapping purposes, we can just show this as a point location. 
![sudden_ranch_parcels](https://user-images.githubusercontent.com/18059717/44547812-11189700-a6d1-11e8-8e07-317092cbbec1.png)

d.	Calculate GIS acres for all ownership tracts
e.	Note, as we finalize ownership tracts, additional parcels may be merged (e.g. with similar ownership names)
2)	Create initial map of ownership tracts (later we will develop a property priority map) 
a.	Create page or tabloid size map like the Coastal Santa Ynez Mountains West map
b.	Show all ownership tracts within the mapping area of this map but query out Dangermond, Sudden Ranch (show as a point location) and ownership tracts that are protected.
c.	Let’s look at showing ownership tracts that are >100 acres differently than tracts that are < 100 acres.  Either query out the <100 acres tracts or show both but highlight the >100 acre tracts and only label these with ownership names and acres
d.	Add protected lands (CPAD and CCED), roads, rivers and label features
e.	Add CAP site area boundary
f.	Add CNDDB occurrences if there is room
3)	Hopefully, we can use this map with input from Mark Reynolds to narrow down this group to a select/small group of potential priority ownership tracts. Once we've done this, you should let me know (or if I’m away, Katie) so we can add these to our TRACTS core dataset to run our conservation accounting report in order to compare metrics between properties.  Once we establish a select group of potential  priority properties, then I think it would make sense to develop a new map.
